import os

from PIL import Image
from tqdm import tqdm

from deeplab import DeeplabV3
from utils.utils_metrics import compute_mIoU, show_results

'''
Notes for metric evaluation:
1. The images generated by this file are grayscale images, because the values are small, there is no display effect when viewing as PNG format, so it's normal to see nearly all-black images.
2. This file calculates the miou of validation set. Currently this library uses test set as validation set, without separate test set division.
'''
if __name__ == "__main__":
    #---------------------------------------------------------------------------#
    #   miou_mode specifies what to calculate when running this file
    #   miou_mode=0 represents entire miou calculation process, including getting prediction results and calculating miou.
    #   miou_mode=1 represents only getting prediction results.
    #   miou_mode=2 represents only calculating miou.
    #---------------------------------------------------------------------------#
    miou_mode       = 0
    #------------------------------#
    #   Number of classes + 1, e.g. 2+1
    #------------------------------#
    num_classes     = 3
    #--------------------------------------------#
    #   Classes to distinguish, same as in json_to_dataset
    #--------------------------------------------#
    #name_classes    = ["background","aeroplane", "bicycle", "bird", "boat", "bottle", "bus", "car", "cat", "chair", "cow", "diningtable", "dog", "horse", "motorbike", "person", "pottedplant", "sheep", "sofa", "train", "tvmonitor"]
    name_classes      = ["_background_","cat","coal"]
    #-------------------------------------------------------#
    #   Points to folder where VOC dataset is located
    #   Default points to VOC dataset in root directory
    #-------------------------------------------------------#
    VOCdevkit_path  = 'VOCdevkit'

    image_ids       = open(os.path.join(VOCdevkit_path, "VOC2007/ImageSets/Segmentation/val.txt"),'r').read().splitlines() 
    gt_dir          = os.path.join(VOCdevkit_path, "VOC2007/SegmentationClass/")
    miou_out_path   = "miou_out"
    pred_dir        = os.path.join(miou_out_path, 'detection-results')

    if miou_mode == 0 or miou_mode == 1:
        if not os.path.exists(pred_dir):
            os.makedirs(pred_dir)
            
        print("Load model.")
        deeplab = DeeplabV3()
        print("Load model done.")

        print("Get predict result.")
        for image_id in tqdm(image_ids):
            image_path  = os.path.join(VOCdevkit_path, "VOC2007/JPEGImages/"+image_id+".jpg")
            image       = Image.open(image_path)
            image       = deeplab.get_miou_png(image)
            image.save(os.path.join(pred_dir, image_id + ".png"))
        print("Get predict result done.")

    if miou_mode == 0 or miou_mode == 2:
        print("Get miou.")
        hist, IoUs, PA_Recall, Precision = compute_mIoU(gt_dir, pred_dir, image_ids, num_classes, name_classes)  # Execute function to calculate mIoU
        print("Get miou done.")
        show_results(miou_out_path, hist, IoUs, PA_Recall, Precision, name_classes)